## Analyzing and Picking top 5 Stocks

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [3]:
# read csv file 
stocks = pd.read_csv('../data/stocks_closing_info_2015.csv').set_index('Ticker Symbol').round(2)
stocks

,Period Ending,Net Income,Profit Margin,Quick Ratio,Total Assets,Total Liabilities,Earnings Per Share,Estimated Shares Outstanding,Total Current Assets,Total Current Liabilities,Closing Price
Ticker Symbol,,,,,,,,,,,
AAL,2015-12-31,7.610000e+09,19.0,67.0,4.841500e+10,4.278000e+10,11.39,6.681299e+08,9.985000e+09,1.360500e+10,42.80
ABBV,2015-12-31,5.144000e+09,23.0,134.0,5.305000e+10,4.910500e+10,3.15,1.633016e+09,1.631400e+10,1.089400e+10,59.80
ABT,2015-12-31,4.423000e+09,22.0,126.0,4.124700e+10,2.003600e+10,2.94,1.504422e+09,1.415500e+10,9.186000e+09,45.27
ADM,2015-12-31,1.849000e+09,3.0,101.0,4.015700e+10,2.224200e+10,2.99,6.183946e+08,2.182900e+10,1.350500e+10,36.88
ADS,2015-12-31,5.965410e+08,9.0,254.0,2.242183e+10,2.041180e+10,8.91,6.695185e+07,1.625042e+10,6.405559e+09,276.77
...,...,...,...,...,...,...,...,...,...,...,...
XYL,2015-12-31,3.400000e+08,9.0,191.0,4.657000e+09,2.573000e+09,1.88,1.808511e+08,2.005000e+09,8.230000e+08,36.87
YHOO,2015-12-31,-4.359082e+09,88.0,588.0,4.520397e+10,1.616043e+10,-4.64,9.394573e+08,7.507319e+09,1.277380e+09,33.37
ZBH,2015-12-31,1.470000e+08,2.0,223.0,2.721950e+10,1.733160e+10,0.78,1.884615e+08,5.862900e+09,1.617900e+09,102.47
ZION,2015-12-31,3.094710e+08,14.0,NaN,5.966952e+10,5.216201e+10,1.20,2.578925e+08,0.000000e+00,0.000000e+00,27.47
ZTS,2015-12-31,3.390000e+08,7.0,133.0,7.913000e+09,6.845000e+09,0.68,4.985294e+08,3.830000e+09,1.781000e+09,48.26

In [4]:
# Filter list to stock price is smaller than $100
priced_filtered = stocks.loc[
    stocks['Closing Price'] < 100,
    :
]

In [5]:
priced_filtered

,Period Ending,Net Income,Profit Margin,Quick Ratio,Total Assets,Total Liabilities,Earnings Per Share,Estimated Shares Outstanding,Total Current Assets,Total Current Liabilities,Closing Price
Ticker Symbol,,,,,,,,,,,
AAL,2015-12-31,7.610000e+09,19.0,67.0,4.841500e+10,4.278000e+10,11.39,6.681299e+08,9.985000e+09,1.360500e+10,42.80
ABBV,2015-12-31,5.144000e+09,23.0,134.0,5.305000e+10,4.910500e+10,3.15,1.633016e+09,1.631400e+10,1.089400e+10,59.80
ABT,2015-12-31,4.423000e+09,22.0,126.0,4.124700e+10,2.003600e+10,2.94,1.504422e+09,1.415500e+10,9.186000e+09,45.27
ADM,2015-12-31,1.849000e+09,3.0,101.0,4.015700e+10,2.224200e+10,2.99,6.183946e+08,2.182900e+10,1.350500e+10,36.88
AEE,2015-12-31,6.360000e+08,10.0,66.0,2.364000e+10,1.669400e+10,2.60,2.446154e+08,1.917000e+09,2.093000e+09,44.00
...,...,...,...,...,...,...,...,...,...,...,...
XRX,2015-12-31,4.740000e+08,3.0,109.0,2.481700e+10,1.574300e+10,0.42,1.128571e+09,6.685000e+09,5.254000e+09,10.72
XYL,2015-12-31,3.400000e+08,9.0,191.0,4.657000e+09,2.573000e+09,1.88,1.808511e+08,2.005000e+09,8.230000e+08,36.87
YHOO,2015-12-31,-4.359082e+09,88.0,588.0,4.520397e+10,1.616043e+10,-4.64,9.394573e+08,7.507319e+09,1.277380e+09,33.37
ZION,2015-12-31,3.094710e+08,14.0,NaN,5.966952e+10,5.216201e+10,1.20,2.578925e+08,0.000000e+00,0.000000e+00,27.47
ZTS,2015-12-31,3.390000e+08,7.0,133.0,7.913000e+09,6.845000e+09,0.68,4.985294e+08,3.830000e+09,1.781000e+09,48.26

## Working Capital Ratio 

- Deciding which company stocks are more liquide 

- Ratio should be between 1.5- 2

In [6]:
# working capital ratio = current assets / current liabilities
priced_filtered['Working Capital Ratio'] = priced_filtered['Total Current Assets'] / priced_filtered['Total Current Liabilities']

<ipython-input-6-953dcb37f02f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  priced_filtered['Working Capital Ratio'] = priced_filtered['Total Current Assets'] / priced_filtered['Total Current Liabilities']

In [7]:
working_capital = pd.DataFrame(priced_filtered['Working Capital Ratio']).sort_values(by='Working Capital Ratio', ascending=False).round(2)

working_capital_top = working_capital.loc[
    priced_filtered['Working Capital Ratio'] <= 2,
    :
]
working_capital_top.head()

               Working Capital Ratio
Ticker Symbol
MAT                             1.94
PWR                             1.89
DVA                             1.88
FBHS                            1.87
PNR                             1.87

In [8]:
working_capital = priced_filtered['Working Capital Ratio']

## Quick Ratio 

- Considered to be more consertvative than current ratio

- The higher the ratio result, the better a company's liquidity

In [9]:
quick_ratio = pd.DataFrame(priced_filtered['Quick Ratio']).sort_values(by='Quick Ratio', ascending=False).round(2)
quick_ratio.head()

               Quick Ratio
Ticker Symbol
YHOO                 588.0
FTR                  535.0
AKAM                 377.0
EW                   359.0
EBAY                 349.0

In [10]:
quick_ratio = priced_filtered['Quick Ratio']

## Earnings Per Share (EPS)

- A higher EPS indicates greater value because investors will pay more for a company's shares if they think the company has higher profits relative to its share price.

In [11]:
earnings_per_share = pd.DataFrame(priced_filtered['Earnings Per Share']).sort_values(by='Earnings Per Share', ascending=False).round(2)
earnings_per_share.head()

               Earnings Per Share
Ticker Symbol
UAL                         19.52
PRU                         12.37
AAL                         11.39
LVLT                         9.71
LYB                          9.62

In [12]:
eps = priced_filtered['Earnings Per Share']

## Price to Earnings Ratio (P/E)

- Investors expect higher earnings with higher P/E

In [13]:
# Earnings Per Share/ closing price = percentage - top 5 stocks 
priced_filtered['P/E Ratio'] = priced_filtered['Closing Price']/priced_filtered['Earnings Per Share'] 
earnings_vs_closing = pd.DataFrame(priced_filtered['P/E Ratio']).sort_values(by='P/E Ratio', ascending=False).head()
earnings_vs_closing['P/E Ratio'] = earnings_vs_closing['P/E Ratio'].map(" {:,.2f}".format)
earnings_vs_closing

<ipython-input-13-9637069dea7a>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  priced_filtered['P/E Ratio'] = priced_filtered['Closing Price']/priced_filtered['Earnings Per Share']

              P/E Ratio
Ticker Symbol
CXO              169.59
KMI              145.40
EQT               91.80
SE                81.83
BMY               73.96

In [14]:
pe_ratio = priced_filtered['Closing Price']/priced_filtered['Earnings Per Share']

## Debt to Equity ratio 

The optimal debt-to-equity ratio will tend to vary widely by industry, but the general consensus is that it should not be above a level of 2.0.

In [30]:
# Find shareholders equity
priced_filtered['Shareholders Equity'] = priced_filtered['Total Assets']-priced_filtered['Total Liabilities']

<ipython-input-30-df0f2d97066c>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  priced_filtered['Shareholders Equity'] = priced_filtered['Total Assets']-priced_filtered['Total Liabilities']

In [33]:
# Debt to equity is total liabilities / Shareholder Equity
priced_filtered['D/E Ratio'] = priced_filtered['Total Liabilities'] / priced_filtered['Shareholders Equity']

<ipython-input-33-2e33f48dcbc1>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  priced_filtered['D/E Ratio'] = priced_filtered['Total Liabilities'] / priced_filtered['Shareholders Equity']

In [34]:
# D/E should not be above 2 - 5 top slowest stocks 
debt_vs_equity = pd.DataFrame(priced_filtered['D/E Ratio']).sort_values(by='D/E Ratio', ascending=True).round(2).head()
debt_vs_equity

               D/E Ratio
Ticker Symbol
WYNN              -94.97
MAS               -42.96
CL                -40.99
IDXX              -18.53
MJN                -7.32

In [35]:
profit_margin = priced_filtered['Profit Margin']
closing_price = priced_filtered['Closing Price']

In [36]:
# create a new dataframe with only the information we need 
final_table = pd.DataFrame({
    'Stock Price': closing_price,
    'Profit Margin': profit_margin,
    'Working Capital Ratio': working_capital,
    'Quick Ratio': quick_ratio,
    'Earning Per Share': eps,
    'P/E Ratio': pe_ratio,
    'D/E Ratio': de_ratio                      
})

final_table

,Stock Price,Profit Margin,Working Capital Ratio,Quick Ratio,Earning Per Share,P/E Ratio,D/E Ratio
Ticker Symbol,,,,,,,
AAL,42.80,19.0,0.733921,67.0,11.39,3.757682,7.591837
ABBV,59.80,23.0,1.497522,134.0,3.15,18.984127,12.447402
ABT,45.27,22.0,1.540932,126.0,2.94,15.397959,0.944604
ADM,36.88,3.0,1.616364,101.0,2.99,12.334448,1.241529
AEE,44.00,10.0,0.915910,66.0,2.60,16.923077,2.403398
...,...,...,...,...,...,...,...
XRX,10.72,3.0,1.272364,109.0,0.42,25.523810,1.734957
XYL,36.87,9.0,2.436209,191.0,1.88,19.611702,1.234645
YHOO,33.37,88.0,5.877123,588.0,-4.64,-7.191810,0.556421
ZION,27.47,14.0,NaN,NaN,1.20,22.891667,6.947969
ZTS,48.26,7.0,2.150477,133.0,0.68,70.970588,6.409176

## Ranking 

- We decided to rank the stocks by:
    - Profit Margin = %10
    - Working Capital Ratio = %35 
    - Quick Ratio = %10
    - EPS = %30
    - D/E Ratio = %25

In [41]:
# find the stock's ranking to find the top 5 stocks 
final_table['Ranking'] = (0.10*final_table['Quick Ratio']+
                          0.10*final_table['Profit Margin']+
                          0.35*final_table['Working Capital Ratio']+
                          0.30*final_table['Earning Per Share']+ 
                          0.25*final_table['D/E Ratio']
)
                        

top_stocks = final_table.sort_values(by='Ranking', ascending=False).round(2)
top_stocks

,Stock Price,Profit Margin,Working Capital Ratio,Quick Ratio,Earning Per Share,P/E Ratio,D/E Ratio,Ranking
Ticker Symbol,,,,,,,,
YHOO,33.37,88.0,5.88,588.0,-4.64,-7.19,0.56,68.40
FTR,4.66,4.0,5.35,535.0,-0.29,-16.07,3.82,56.64
AKAM,52.90,15.0,3.77,377.0,1.80,29.39,0.34,41.14
EW,79.21,20.0,4.30,359.0,2.30,34.44,0.62,40.25
EBAY,27.75,20.0,3.49,349.0,1.43,19.41,1.70,38.98
...,...,...,...,...,...,...,...,...
UNM,33.52,8.0,NaN,NaN,3.51,9.55,5.99,NaN
VTR,56.63,13.0,NaN,NaN,1.26,44.94,1.33,NaN
WFC,54.89,25.0,NaN,NaN,4.18,13.13,8.26,NaN
XL,39.82,13.0,NaN,NaN,4.22,9.44,4.03,NaN
ZION,27.47,14.0,NaN,NaN,1.20,22.89,6.95,NaN

In [42]:
top_stocks.to_csv("../data/top_stocks.csv")